spring:
  jpa:  
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:  
         hibernate:   
               dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
  datasource:
    url: 
    username: 
    password: 
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    platform: development

   