spring:
  jpa:  
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:  
         hibernate:   
               dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net/heroku_ac7678eb9894be7?useSSL=false&characterEncoding=UTF-8
    username: b7d31ac7686ca2
    password: f0fb84a9
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    platform: development

   